version: '3'
services:

  qtim-db:
    image: postgres
    restart: always
    networks:
      - app-network
    environment:
      POSTGRES_DB: qtimdb
      POSTGRES_USER: qtimuser
      POSTGRES_PASSWORD: qtimpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  qtim-service:
    build:
      context: .
      dockerfile: .Dockerfile
    restart: always
    networks:
      - app-network
    depends_on:
      - qtim-db
      - redis
    environment:
      TYPEORM_HOST: qtim-db
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: qtimuser
      TYPEORM_PASSWORD: qtimpassword
      TYPEORM_DATABASE: qtimdb
    ports:
      - "3000:3000"  
    volumes:
    - ./:/app

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network


networks:
  app-network:

volumes:
  postgres_data:
    driver: local
